name: job-matrix

on:
  push:
  
jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu:18.04, ubuntu:20.04]
        node: [12, 14]
        exclude:
        - os: ubuntu-18.04
          node: 12
          
    #runs-on: ${{ matrix.os }} 1
    runs-on: self-hosted 
    container: ${{ matrix.os }}   
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
      - name: Print OS-release
        run: cat /etc/os-release
        
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test

